---
functional:
# Механика и возможности игры:
  - Пользователь может создать игру
  - Пользователь должен видеть редактор во время игры и может писать в нем код
  - Пользователь должен видеть во время игры в режиме онлайн код своего соперника, время игры, задание  
  - Пользователь может выбирать язык программирования из возможных во время игры
  - Пользователь может выбрать уровень сложности 
  - Пользователь может выбрать определенное задание из списка
  - Пользователь может проверять написанный код неограниченное количество раз во время игры
  - Пользователь может играть против бота
  - Во время игры пользователи могут общаться через чат
  - Дожна быть возможность выбора языка текста задания (русский или английский)
  - Другие пользователи должны иметь возможность следить за ходом игры
  - Пользователь должен иметь возможность играть с другом (другой зарегистрированный пользователь)
# Авторизация:
  - Пользователь может зарегистрироваться на сайте
  - Пользователь может авторизоваться на сайте 
# Профайл:
  - В профайле должна сохраняться историй игр и отражается количество сыгранных игр
  - В профайле должен отражаться рейтинг пользователя
  - Дожна быть возможность просмотра завершенной игры
  - За завершенные игры должны начисляться и суммироваться очки
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Система должна определять победителя и выводить инофрмацию об этом на экран по завершению игры
  - Пользователь может покинуть игру до завершения времени
  - Пользователь может сдаться досрочно
  - Пользователь должен иметь возможность открывать и редактировать свой профайл
  
  
